### ISSUE TITLE
Crash when opening a Swift file

### ISSUE THREAD

**Issue by igorkulman** [samuser107/zed-swift-extension#1]
On Zed 0.123.3 I installed the Swift extension v0.0.3 from the extensions section. Now every time try open a swift file with Zed it immediately crashes.

Here is the log.
[crash.log](https://github.com/samuser107/zed-swift-extension/files/14385631/crash.log)

**Comment by samuser107** [comment]
Thanks to let me know. Apparently it's a bug from Zed, like mentioned here :
https://github.com/zed-industries/extensions/pull/106#issuecomment-1961765621
