### ISSUE TITLE
This extension does not load on Zed 0.123.6

### ISSUE THREAD

**Issue by tonycoco** [samuser107/zed-swift-extension#3]
I do not get any syntax highlighting with the latest version of Zed and fully updated extension for Swift.

What steps are required to install?

**Comment by deevus** [comment]
Also happening with 0.124.7

**Comment by deevus** [comment]
Ok so it's because they disabled Swift explicitly in the build of Zed

https://github.com/zed-industries/extensions/pull/221#issuecomment-1965705945

**Comment by samuser107** [comment]
@tonycoco @deevus Yes zed disabled the extension because it used an older version of a tree sitter, now that's supposed to be fixed i'm trying to make it available again. Sorry for that
